resources:
- name: etcher-git
  type: git
  source:
    uri: https://github.com/resin-io/etcher.git
    branch: concourse-test
    disable_ci_skip: true

jobs:
- name: tests-darwin

  # Make the job results accessible to
  # un-authenticated users
  public: true

  plan:
  - get: etcher-git

    # Trigger this job if the resource has a new
    # version. If this is false, the job can only
    # be started from the web UI.
    trigger: true

  - task: dependencies
    config:
      platform: darwin
      inputs:
        - name: etcher-git
      outputs:
        - name: etcher-electron
      run:
        path: /bin/bash
        args:
          - -exc
          - |
            cp -a etcher-git/. etcher-electron
            make -C etcher-electron electron-develop
            cd etcher-electron/node_modules
            tar czf bin.tar.gz .bin

  # TODO: Use an aggregate to parallelize these

  - task: lint
    config:
      platform: darwin
      inputs:
        - name: etcher-electron
      run:
        path: /bin/bash
        dir: etcher-electron
        args:
          - -exc
          - |
            tar fx ./node_modules/bin.tar.gz -C ./node_modules
            make lint

  - task: test
    config:
      platform: darwin
      inputs:
        - name: etcher-electron
      run:
        path: /bin/bash
        dir: etcher-electron
        args:
          - -exc
          - |
            tar fx ./node_modules/bin.tar.gz -C ./node_modules
            make test

  - task: sanity-checks
    config:
      platform: darwin
      inputs:
        - name: etcher-electron
      run:
        path: /bin/bash
        dir: etcher-electron
        args:
          - -exc
          - |
            tar fx ./node_modules/bin.tar.gz -C ./node_modules
            make sanity-checks
